name: Publish to github pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Haskell
        run: |
          docker run -td --name builder --rm -v $(pwd):/srv -v ~/.cabal:/root/.cabal -w /srv haskell:8.10 bash

      - name: Build
        run: |
          docker exec builder bash -c "cabal update && cabal build && cabal install"
          docker exec builder bash -c "cabal exec site clean && cabal exec site build"

      - name: Deploy
        run: |
          git config user.name "GithubAction"
          git config user.email "you@example.com"

          git fetch --all
          git checkout -b gh-page origin/gh-page
          git reset --hard $(git rev-list --max-parents=0 --abbrev-commit HEAD)

          cp -a _site/. ./
          git add -A
          git commit -m "Publish"
          git push origin gh-page -f
